packages/core/README.md

just noticed that my icomoon svg's aren't showing up as intended, using fill instead of color worked.

some svg's require to use fill for color change

---

.changeset/wet-meals-share.md
demo/src/pages/map.astro
packages/core/lib/resolver.ts

Closes #15. My caching logic was not handling parallel requests properly, so when Astro used `Promise.all()` to render children in a map, only the first request was resolving properly.

fix(#15): fix parallelism issue with remote cache

---

.changeset/lazy-tips-lie.md
.changeset/tall-needles-admire.md
demo/package.json
demo/src/icons/heroicons.ts
demo/src/icons/radix.ts
packages/core/index.ts
packages/core/lib/Icon.astro
packages/core/lib/Spritesheet.astro
packages/core/lib/createIconPack.ts
packages/core/lib/utils.ts
packages/core/pack.ts
packages/core/package.json
packages/www/package.json
yarn.lock

Now that Vite has been upgraded in Astro, you can use it in astro-icon to gain support for the static build.
I believe this is equivalent to what was happening before and it's working in the `www/` app!
Note that this would be a breaking change since it requires Astro 0.23, so you might want to do a prerelease (up to you of course).

Compatibility with the static build

---

packages/core/README.md

The `README.md` file didn't contain a reference to the official icon sets reference of *Iconify*. This PR includes a reference to https://icon-sets.iconify.design/.

Referenced the official icon sets reference

---

.changeset/honest-swans-bake.md
demo/astro.config.mjs
demo/package.json
packages/core/lib/utils.ts
packages/core/package.json
yarn.lock

Vite build warning (astro@0.25.4)
> (!) import.meta.glob('...', { assert: { type: 'raw' }}) is deprecated. Use import.meta.glob('...', { as: 'raw' }) instead.
- This also adds back the keywords in `astro-icon`'s package.json, not sure why the CI action changed these in [73e4b9b](https://github.com/natemoo-re/astro-icon/commit/73e4b9b5f853b6d7a3189a00355be5304706911b) though 🤔

Removes the deprecation warning for import.meta.globEager

---

.changeset/green-camels-teach.md
demo/src/icons/custom.ts
demo/src/pages/index.astro
packages/core/lib/utils.ts

The following PR passes `Icon` properties down to custom resolver in order to allow building custom asset URLs that depend not only on icon name, but also size.

feat: pass props to custom resolver

---

.changeset/eleven-rocks-complain.md
packages/core/lib/Spritesheet.astro

I noticed that some icons (like `logos:vitejs`) are not showing in Chrome, but they work fine in Firefox.
After some investigation, it seems that using `display: none` on the spritesheet's SVG causes gradients to don't work in Chrome. Resources:
- this old CSS-Tricks topic: https://css-tricks.com/forums/topic/gradients-and-hiding-symbol-defining-svg-blocks-in-html/
- this fairly new issue on SO: https://stackoverflow.com/questions/66199983/why-is-my-svgs-radialgradient-not-showing-in-chrome-based-browsers-but-does-in
I also created a [demo in CodePen to reproduce the issue](https://codepen.io/marco_solazzi/pen/abGKYqe) (screenshot below):
This PR uses another technique to hide the spritesheet that should make everything work in Chrome.
For reference, here are my system's details:
``` …
```

fix: show icon with gradients in Chrome

---

.changeset/quiet-insects-cover.md
packages/core/lib/createIconPack.ts

Updates node dependencies to use the `node:` prefix. 
**Benefits:**
- More explicit protocol makes it more readable and also makes it clear that a built-in module is being imported. Since there are a lot of built-in ones, this extra information is useful for beginners or for someone who might not know about one of them.
- It reduces the risk of a module present in node_modules overriding the newer imports.
Supported in Node.js starting:
- v16.0.0, v14.18.0 (ESM import and CommonJS require())
- v14.13.1, v12.20.0 (only ESM import)
Supported in TypeScript by the latest versions of `@types/node`.

Chore: use `node:` prefix on node dependencies

---

.changeset/fuzzy-insects-flash.md
packages/core/lib/Sprite.astro
packages/core/lib/Spritesheet.astro
packages/core/lib/context.ts

This PR updates the `Sprite` context to utilize `Astro.request` instead of hacking the Astro `SSRResult` for tracking the `Sprite` usages. This also removes a few `@ts-ignore`s which are always nice to remove.
This replaces #58 with a correct fix.

Update Sprite context to use `Astro.request`

---

.changeset/sweet-foxes-jam.md
packages/core/README.md

Update the `README.md` file to better explain Icon Packs, styling, and the icon fallback.
Closes #40
Closes #53 
Closes #84

docs: update core README

---

.github/workflows/ci.yml
demo/src/content/config.ts
packages/core/components.d.ts
packages/core/integration.d.ts
pnpm-lock.yaml

The v1 branch utilizes `pnpm` so this PR updates the CI to also utilize `pnpm`. These changes are based on the pnpm guide for using Github Actions: https://pnpm.io/continuous-integration#github-actions

[v1] chore: update CI to use pnpm

---

packages/core/src/vite-plugin-astro-icon.ts

The `importDirectory` function will throw if the passed `dir` is not present. This will catch any error from the local collection generation and warn about it. This should be the only thing that triggers this catch.

fix: prevent missing local collection from failing build

---

.changeset/fuzzy-beers-count.md
packages/core/components/Icon.astro
packages/core/src/vite-plugin-astro-icon.ts

Moves the warning about a missing local directory/collection to only apply on usage of a local icon

move warning about local directory to on use

---

.changeset/violet-experts-travel.md
packages/core/src/vite-plugin-astro-icon.ts

As pointed out in #100, it seems we had a bad merge conflict resolution. This properly passes the options through.

fix: correctly pass SVGO Options

---

.changeset/tough-wombats-hang.md
packages/core/lib/utils.ts

Build an astro v3.0 project with `astro-icon`, and get a warnning:
Maybe it's because of the v3.0 change: https://docs.astro.build/en/guides/upgrade-to/v3/#changed-default-verbatimmodulesyntax-in-tsconfigjson-presets

fix type import

---

.changeset/great-carpets-hide.md
packages/core/lib/createIconPack.ts

When trying to build a site with a custom icon pack using the `astro/tsconfigs/strict` [TSConfig](https://docs.astro.build/en/guides/typescript/#setup), `tsc --noEmit` fails:
> Error: node_modules/.pnpm/astro-icon@0.8.1/node_modules/astro-icon/lib/createIconPack.ts(18,45): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
>   Type 'undefined' is not assignable to type 'string'.
>  ELIFECYCLE  Command failed with exit code 2.
It turns out that [`resolvePackage` may return `undefined`](https://github.com/sindresorhus/resolve-pkg/blob/72020a878937aafb9ec42eaa2692bf6101c69123/index.js#L19-L21), therefore this edge-case should be handled.

fix(createIconPack): handle unresolved modules

---

.changeset/young-chicken-hear.md
packages/core/lib/createIconPack.ts

The existence of a file shouldn’t be checked in advance, as that doesn’t guarantee that the given file can actually be read. Therefore, our best bet is to just try reading directly from the file and then handle errors.

perf(createIconPack): improve local icon resolution

---

.changeset/great-cameras-drum.md
packages/core/lib/utils.ts

Hey folks! Sorry I've been away! Astro itself has been my main focus for a while and it's difficult to find time for other maintenance.
Got some reports of `astro-icon` breaking in Astro 4 and tracked it to an old API that was removed in Vite 5. This PR fixes that and will result in a patch release.
I will be opening an issue to share my thoughts on the future of `astro-icon` soon!

Replace `globEager` to fix Vite 5 incompatability

---

.changeset/six-parents-know.md
packages/core/package.json
packages/core/src/loaders/loadIconifyCollections.ts
pnpm-lock.yaml

Instead of using `npm ls` to get the installed packages, we just read `package.json` directly. Although this has the drawback of not supporting nested dependencies, it does sidestep a number of issues when `NODE_ENV=production` or using different package managers with their own heuristics for the `list` command.
Fixes #165, fixes #171, fixes #173

Read `package.json` to determine installed icon packs

---

.changeset/two-lizards-double.md
packages/core/src/vite-plugin-astro-icon.ts

Fixes #176
The warning for missing collections was accidentally logged before the local collection was loaded.
The log message has also been improved to include the directory of the local icon source first.

Removes warning when no icon packs are found

---

.changeset/hungry-steaks-relax.md
demo/src/pages/index.astro
packages/core/src/loaders/loadLocalCollection.ts

Fixes #178
**BREAKING**: Subdirectory prefixes are **required** for local icons.
This fixes a regression introduced in v1 and matches the previous v0 `name` behavior.
As an example, the `src/icons/logos/astro.svg` file could previously be referenced by the name `astro`. It should correctly be referenced by the name `logos/astro`.
**Before**
```jsx
<Icon name="astro" />
```
**After**
```jsx
<Icon name="logos/astro" />
```

Match v0 name behavior for local icons

---

.changeset/heavy-insects-yawn.md
packages/core/src/loaders/loadLocalCollection.ts

Closes #183.
Previously, invalid local icons would cause the entire local icon set to silently fail.
By using `ignoreImportErrors: 'warn'`, invalid icons are now logged and ignored while valid icons are properly loaded.

Warn and continue when local icon cannot be loaded

---

packages/core/components/Icon.astro

TypeScript was detecting the error throw the node_modules folder, so I fixed it.

Custom Component Error Class & Icon name variable used.

---

packages/core/components/Icon.astro

Currently if no width or height attributes provided to Icon component - it receives some weird rem units. This fix allows inheriting view box values if no width / height is provided.

fix: inherit viewbox width / height of none provided

---

packages/www/src/content/docs/guides/deployment.mdx

A very small PR, when reading docs I noticed a missing word:
> ...should take special _ when using Astro Icon
So I added the word 'care':
> ...should take special care when using Astro Icon

docs(typo): Add missing word 'care'

---

.changeset/afraid-rivers-agree.md
packages/core/components/Icon.astro

Fixes #196
Rolls back the changes introduced in #186. We will need to find a different API for automatically sizing SVGs without forcing everyone into a square aspect ratio.

Revert sizing change

---

.changeset/nine-waves-film.md
demo/src/pages/index.astro
packages/core/components/Icon.astro

Resolves #193, resolves #194
Adds support for a new `is:inline` directive which bypasses the automatic sprite optimization and just inlines the SVG directly. This directive addresses the use cases outlined in #193 and #194.

Add support for `is:inline` directive

---

.changeset/nine-poems-teach.md
packages/core/components/Icon.astro
packages/www/src/content/docs/guides/components.mdx

Fixes #213
* Made `width`, `height` and `size` able to accept a `string` value as well as a `number` value (i.e. for using `rem`, `px`, etc.)
However, this is similar to the inherent attributes associated with an `<svg>` tag:
So - an alternate solution may be just removing these attributes from the props entirely, and just relying on the `extends HTMLAttributes<"svg">` instead.

Types - Added Better Typings for Width, Height + Size

---

.changeset/rare-rules-tie.md
packages/core/package.json
pnpm-lock.yaml

Iconify tools had a type error with a specific 'cheerio' package that caused astro-icon to fail on build with Astro. Bumping the package fixes the type error.
See this issue for more details: https://github.com/natemoo-re/astro-icon/issues/210

Bump @iconify/tools to fix type errors

---

.changeset/curvy-lions-dream.md
packages/core/README.md
packages/core/components/Icon.astro
packages/www/src/content/docs/guides/components.mdx

I was using astro-icon for the first time as a part of a [course](https://learnastro.dev/) I'm taking, and I was curious about some accessibility details. Looking into it, I saw that astro-icon supports the `title` tag, but doesn't yet support the `desc` tag. 
`<desc>` isn't used as commonly as `<title>`, but can be an important tag for complex svgs. Read more about it here: [https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements](https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements).
I used yalc to link my locally-built astro-icon package and was able to pass a `desc` prop to my icon, which was added as a `desc` tag. Let me know if there are other ways to test, or edge cases I should look into.

feat(desc): support desc svg tag.

---

.changeset/dry-peas-prove.md
packages/core/components/Icon.astro

fix: move viewBox to symbol

---

.changeset/eight-sloths-dream.md
packages/core/src/loaders/loadIconifyCollections.ts

fix: handle duplicate icon entries in include config

---

.changeset/young-dots-tell.md
packages/core/components/Icon.astro
packages/www/src/content/docs/guides/components.mdx

fix(Icon): switch to non-deprecated href attribute

---

.changeset/chilled-fans-beg.md
packages/core/src/vite-plugin-astro-icon.ts

Currently, the generated icon type definitions (`.astro/icon.d.ts`) do not include aliases from IconifyJSON.
In my case, I am using Material Design Icons as `<Icon name="mdi:external-link" />` and adding `/// <reference path="../.astro/icon.d.ts" />` to `src/env.d.ts`. However, `astro check` fails due to a type error. This is because "mdi:external-link" is an alias of "mdi:open-in-new" and the alias is not recognized in the type definitions.
This fix updates the icon type generation process to include aliases from IconifyJSON, allowing type checking to recognize both original names and their aliases. Additionally, the hash calculation has been adjusted to account for these aliases.

fix: include aliases in icon type definitions and hash calculation
